name: Directory push/pop
author: Philip Colmer (Linaro Ltd)
branding:
  icon: "archive"
  color: "green"
description: |
  Syncs a named directory from a cache and optionally back again.
inputs:
  cacheDirectory:
    description: "Path to the directory used to store directories"
    required: true
  namedDirectory:
    description: "Name of the directory to sync"
    required: true
  destinationDirectory:
    description: "Where to sync the named directory to"
    required: false
  popAtEnd:
    description: "Sync back to cache at the end of the workflow"
    default: true
    required: false
  deleteAtEnd:
    description: "Delete named directory at the end of the workflow"
    default: true
    required: false
runs:
  using: "node16"
  main: 'directory-push.js'
  post: 'directory-pop.js'
